// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCRUS1AVTEtgPtAlmodq1n8VRQ7ZYbt4',
    appId: '1:1087773508927:web:a7b3e54878ca5079bf7f8a',
    messagingSenderId: '1087773508927',
    projectId: 'autimo-test-cdc6b',
    authDomain: 'autimo-test-cdc6b.firebaseapp.com',
    storageBucket: 'autimo-test-cdc6b.appspot.com',
    measurementId: 'G-D9F160WZWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgoTI_nd1oNP-vAfO7zggVQAM2r_jCZ4',
    appId: '1:1087773508927:android:23a94fba18dacc9cbf7f8a',
    messagingSenderId: '1087773508927',
    projectId: 'autimo-test-cdc6b',
    storageBucket: 'autimo-test-cdc6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQFHVsL379YsFlIF1q8l-qrMXeZfVv5Q',
    appId: '1:1087773508927:ios:d2e3e9be5b69f23dbf7f8a',
    messagingSenderId: '1087773508927',
    projectId: 'autimo-test-cdc6b',
    storageBucket: 'autimo-test-cdc6b.appspot.com',
    iosClientId: '1087773508927-7ldg03mpc40gvsk6oke2gubprdphaut6.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAutimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQFHVsL379YsFlIF1q8l-qrMXeZfVv5Q',
    appId: '1:1087773508927:ios:598e7b153be11435bf7f8a',
    messagingSenderId: '1087773508927',
    projectId: 'autimo-test-cdc6b',
    storageBucket: 'autimo-test-cdc6b.appspot.com',
    iosClientId: '1087773508927-5flcgkiqvii3mu7kq0iih467f97ae3v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAutimo.RunnerTests',
  );
}
